language: python
python:
- "2.7"
- "3.3"
- "3.4"
- "3.5"
env:
- PHPENV_VERSION="7.0"
- PHPENV_VERSION="7.1"
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libzbar-dev
install:
- pip install coveralls
script:
- ls /home/travis/.phpenv/versions
- php --version
- phpenv local $PHPENV_VERSION
- php --version
- cd python; coverage run --source . ./setup.py test
- cd ../php; composer install; composer test
after_success:
- coveralls

