language: python
python:
- "2.7"
- "3.5"
- "3.6"
- "3.9"
env:
- PHPENV_VERSION="7.2"
before_install:
- phpenv local $PHPENV_VERSION || (phpenv versions && false)
- php --version
- sudo apt-get -qq update
- sudo apt-get install -y libzbar-dev
install:
- pip install coveralls
script:
- cd python; coverage run --source . ./setup.py test
- cd ../php; composer install; composer test
after_success:
- coveralls

