name: CI

on:
  - push # git push
  - pull_request # PR from other clones
  - workflow_dispatch # Explicit launch

jobs:
  build-python:
    runs-on: ubuntu-latest
    env:
      TRAVIS: 'true' # Skip tests requiring data
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.12'
    name: Python ${{ matrix.python-version }}
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python dependencies
        working-directory: python
        run: |
          pip install requests
          pip install -e .
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            coveralls
            pytest-cov
      - name: Python tests
        working-directory: python
        run: |
          pytest --cov intercoop intercoop

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: Unit tests
          base-path: python/

  build-php:
    runs-on: ubuntu-latest
    env:
      TRAVIS: 'true' # Skip tests requiring data
    strategy:
      matrix:
        php-version:
          - '7.2'
          - '7'
          #- '8.0'
    name: PHP ${{ matrix.php-version }}
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          sudo apt install -y libzbar-dev

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: PHP dependencies
        working-directory: php
        run: |
          composer install
      - name: PHP tests
        working-directory: php
        run: |
          composer test

  coveralls_finish:
    needs: build-python
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
        base-path: python/
