# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TRAVIS: 'true' # Skip tests requiring data
    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
        php-versions:
          - '7.2'
          - '8.0'
    name: Python ${{ matrix.python-version }} PHP ${{ matrix.php-version }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2
      - name: PHP environment and dependencies
        working-directory: php
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}
      - name: PHP implementation tests
        working-directory: php
        run: composer test

      - name: Python environment
        working-directory: python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python implementation tests
        working-directory: python
        run: coverage run --source . ./setup.py test
      - name: Install dependencies
        run: |
          ./setup.py develop
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            coveralls
      - name: Unit tests
        run: |
          coverage run --source tomatic ./setup.py test

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: Unit tests

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
